/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thiago
 */
public class ComissaUI extends javax.swing.JFrame {

    public ArrayList<Comissao> comissoes;

    /**
     * Creates new form ComissaUI
     */
    public ComissaUI() {
        initComponents();

        comissoes = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        GuiaBox = new javax.swing.JComboBox<>();
        ConsumoField = new javax.swing.JTextField();
        PaxField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        FinalizarButton = new javax.swing.JButton();
        ContaApoioField = new javax.swing.JTextField();
        PaxPraiaField = new javax.swing.JTextField();
        ConsumoTotalField = new javax.swing.JTextField();
        DiaField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComissionamentoPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ConsumoApoioField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GuiaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alessandro", "Alexandre", "Andressa", "Andrucho", "Aracele","Bug. Antonio", "Bug. Bruno", "Bug. Diego", "Bug. Felipe", "Bug. Gustavo", "Bug. Jadsom", "Bug. Jose Carlos", "Bug. Lucio",  "Bug. Marcus", "Bug. Neto", "Bug. Pablo", "Bug. Paulo", "Bug. Tiba", "Bug. Vamberto", "Bug. Walter", "Bug. Zé Carlos", "Bylylyco", "Cassiana", "Davidson", "Elizabeth", "Eric", "Fernanda", "Henrique", "Irlha", "Italo", "Jamile", "Jeane", "Juciele", "Karla", "Lilian", "Margarida", "Maurício", "Monica", "Natalia", "Persio", "Ricardo", "Rita", "Solange", "Thaline", "Ubiratã", "Victor", "William", "Yrys" }));

        ConsumoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsumoFieldActionPerformed(evt);
            }
        });

        PaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaxFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FinalizarButton.setText("Finalizar");
        FinalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarButtonActionPerformed(evt);
            }
        });

        ContaApoioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaApoioFieldActionPerformed(evt);
            }
        });

        PaxPraiaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaxPraiaFieldActionPerformed(evt);
            }
        });

        ConsumoTotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsumoTotalFieldActionPerformed(evt);
            }
        });

        DiaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ComissionamentoPane);

        jLabel1.setText("Guia");

        jLabel2.setText("Consumo");

        jLabel3.setText("Pax");

        jLabel4.setText("Apoio praia");

        jLabel6.setText("Pax praia");

        jLabel7.setText("Apurado do dia");

        jLabel8.setText("dd/mm");

        ConsumoApoioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsumoApoioFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("consumo apoio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(GuiaBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 96, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContaApoioField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(FinalizarButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ConsumoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(ConsumoApoioField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(PaxPraiaField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PaxField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))))))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ConsumoTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsumoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContaApoioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsumoApoioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaxPraiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsumoTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(FinalizarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Comissao com = new Comissao((String) GuiaBox.getSelectedItem(), Integer.parseInt(PaxField.getText()), getfloat(ConsumoField.getText()));
        comissoes.add(com);
        ComissionamentoPane.setText(getPreview());
        limpaGuia();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaxFieldActionPerformed

    private void ContaApoioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaApoioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContaApoioFieldActionPerformed

    private void PaxPraiaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaxPraiaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaxPraiaFieldActionPerformed

    private void ConsumoTotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsumoTotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsumoTotalFieldActionPerformed

    private void DiaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaFieldActionPerformed

    private void ConsumoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsumoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsumoFieldActionPerformed

    private void FinalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarButtonActionPerformed
        // TODO add your handling code here:
        float total = getfloat(ConsumoTotalField.getText());
        float luck = getTotalConsumoGuias();
        float apoio = getfloat(ConsumoApoioField.getText());
        float praia = total - apoio - luck;
        int paxApoio = Integer.parseInt(ContaApoioField.getText());
        int paxPraia = Integer.parseInt(PaxPraiaField.getText());
        int paxGuias = getTotalPaxGuia();
        int paxTotal = paxApoio + paxGuias + paxPraia;
        float TMdia = total / paxTotal;
        float TMapoio = apoio / paxApoio;
        float TMPraia = praia / paxPraia;

        String texto = "*PRAIAS DA COSTA DO CONDE " + DiaField.getText() + "*\n\n";
        texto += String.format("TOTAL RECEITA: R$%.2f\n", total);
        texto += String.format("TOTAL DE PAX: %d\n", paxTotal);
        texto += String.format("TM TOTAL: R$%.2f\n\n", TMdia);
        
        texto += String.format("TOTAL LUCK: R$%.2f\n", luck);
        texto += String.format("TOTAL APOIO: R$%.2f\n", apoio);
        texto += String.format("TOTAL PRAIA: R$%.2f\n\n", praia);

        for (Comissao com : comissoes) {
            
            texto += String.format("%1$s - Comissão: R$%2$.2f\n", com.getGuia(), com.comissao);
            texto += String.format("Ticket Médio R$%.2f\n\n", com.TM);
        }

        ComissionamentoPane.setText(texto);

    }//GEN-LAST:event_FinalizarButtonActionPerformed

    private void ConsumoApoioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsumoApoioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsumoApoioFieldActionPerformed

    private void limpaGuia() {
        ConsumoField.setText("");
        PaxField.setText("");
    }

    private int getTotalPaxGuia() {
        int pax = 0;
        for (Comissao com : comissoes) {
            pax += com.getPax();
        }

        return pax;
    }
    
        private float getTotalConsumoGuias() {
        float total = 0;
        for (Comissao com : comissoes) {
            total += com.getConsumo();
        }

        return total;
    }

    private String getPreview() {
        String texto = "";
        for (Comissao com : comissoes) {
            texto += String.format("%1$s - Comissão: R$%2$.2f\n", com.getGuia(), com.comissao);
            texto += String.format("Ticket Médio R$%.2f\n", com.TM);
        }

        return texto;

    }

    private float getfloat(String num){
    num = num.replace(',', '.');
    return new Float(num);
    
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComissaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComissaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComissaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComissaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComissaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ComissionamentoPane;
    private javax.swing.JTextField ConsumoApoioField;
    private javax.swing.JTextField ConsumoField;
    private javax.swing.JTextField ConsumoTotalField;
    private javax.swing.JTextField ContaApoioField;
    private javax.swing.JTextField DiaField;
    private javax.swing.JButton FinalizarButton;
    private javax.swing.JComboBox<String> GuiaBox;
    private javax.swing.JTextField PaxField;
    private javax.swing.JTextField PaxPraiaField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
